/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExchangeIndexRouteImport } from './routes/exchange.index'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ExchangeCheckoutRouteImport } from './routes/exchange.checkout'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeIndexRoute = ExchangeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExchangeRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeCheckoutRoute = ExchangeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ExchangeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/exchange': typeof ExchangeRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/exchange/checkout': typeof ExchangeCheckoutRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/exchange/': typeof ExchangeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/exchange/checkout': typeof ExchangeCheckoutRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/exchange': typeof ExchangeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/exchange': typeof ExchangeRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/exchange/checkout': typeof ExchangeCheckoutRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/exchange/': typeof ExchangeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy'
    | '/exchange'
    | '/sitemap.xml'
    | '/swap'
    | '/exchange/checkout'
    | '/order/$orderId'
    | '/exchange/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy'
    | '/sitemap.xml'
    | '/swap'
    | '/exchange/checkout'
    | '/order/$orderId'
    | '/exchange'
  id:
    | '__root__'
    | '/'
    | '/buy'
    | '/exchange'
    | '/sitemap.xml'
    | '/swap'
    | '/exchange/checkout'
    | '/order/$orderId'
    | '/exchange/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  ExchangeRoute: typeof ExchangeRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwapRoute: typeof SwapRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/': {
      id: '/exchange/'
      path: '/'
      fullPath: '/exchange/'
      preLoaderRoute: typeof ExchangeIndexRouteImport
      parentRoute: typeof ExchangeRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/checkout': {
      id: '/exchange/checkout'
      path: '/checkout'
      fullPath: '/exchange/checkout'
      preLoaderRoute: typeof ExchangeCheckoutRouteImport
      parentRoute: typeof ExchangeRoute
    }
  }
}

interface ExchangeRouteChildren {
  ExchangeCheckoutRoute: typeof ExchangeCheckoutRoute
  ExchangeIndexRoute: typeof ExchangeIndexRoute
}

const ExchangeRouteChildren: ExchangeRouteChildren = {
  ExchangeCheckoutRoute: ExchangeCheckoutRoute,
  ExchangeIndexRoute: ExchangeIndexRoute,
}

const ExchangeRouteWithChildren = ExchangeRoute._addFileChildren(
  ExchangeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  ExchangeRoute: ExchangeRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwapRoute: SwapRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
