/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuyCryptoRouteImport } from './routes/buy-crypto'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExchangeIndexRouteImport } from './routes/exchange.index'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ExchangeCheckoutRouteImport } from './routes/exchange.checkout'
import { Route as ExchangeOrderOrderIdRouteImport } from './routes/exchange.order.$orderId'
import { Route as ApiEmailVerifyCodeRouteImport } from './routes/api/email/verify-code'
import { Route as ApiEmailSendCodeRouteImport } from './routes/api/email/send-code'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCryptoRoute = BuyCryptoRouteImport.update({
  id: '/buy-crypto',
  path: '/buy-crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeIndexRoute = ExchangeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExchangeRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeCheckoutRoute = ExchangeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ExchangeRoute,
} as any)
const ExchangeOrderOrderIdRoute = ExchangeOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => ExchangeRoute,
} as any)
const ApiEmailVerifyCodeRoute = ApiEmailVerifyCodeRouteImport.update({
  id: '/api/email/verify-code',
  path: '/api/email/verify-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendCodeRoute = ApiEmailSendCodeRouteImport.update({
  id: '/api/email/send-code',
  path: '/api/email/send-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buy': typeof BuyRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/dashboard': typeof DashboardRoute
  '/exchange': typeof ExchangeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/verify-email': typeof VerifyEmailRoute
  '/exchange/checkout': typeof ExchangeCheckoutRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/exchange/': typeof ExchangeIndexRoute
  '/api/email/send-code': typeof ApiEmailSendCodeRoute
  '/api/email/verify-code': typeof ApiEmailVerifyCodeRoute
  '/exchange/order/$orderId': typeof ExchangeOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buy': typeof BuyRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/verify-email': typeof VerifyEmailRoute
  '/exchange/checkout': typeof ExchangeCheckoutRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/exchange': typeof ExchangeIndexRoute
  '/api/email/send-code': typeof ApiEmailSendCodeRoute
  '/api/email/verify-code': typeof ApiEmailVerifyCodeRoute
  '/exchange/order/$orderId': typeof ExchangeOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/buy': typeof BuyRoute
  '/buy-crypto': typeof BuyCryptoRoute
  '/dashboard': typeof DashboardRoute
  '/exchange': typeof ExchangeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/verify-email': typeof VerifyEmailRoute
  '/exchange/checkout': typeof ExchangeCheckoutRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/exchange/': typeof ExchangeIndexRoute
  '/api/email/send-code': typeof ApiEmailSendCodeRoute
  '/api/email/verify-code': typeof ApiEmailVerifyCodeRoute
  '/exchange/order/$orderId': typeof ExchangeOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/buy'
    | '/buy-crypto'
    | '/dashboard'
    | '/exchange'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/swap'
    | '/verify-email'
    | '/exchange/checkout'
    | '/order/$orderId'
    | '/exchange/'
    | '/api/email/send-code'
    | '/api/email/verify-code'
    | '/exchange/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/buy'
    | '/buy-crypto'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/swap'
    | '/verify-email'
    | '/exchange/checkout'
    | '/order/$orderId'
    | '/exchange'
    | '/api/email/send-code'
    | '/api/email/verify-code'
    | '/exchange/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/buy'
    | '/buy-crypto'
    | '/dashboard'
    | '/exchange'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/swap'
    | '/verify-email'
    | '/exchange/checkout'
    | '/order/$orderId'
    | '/exchange/'
    | '/api/email/send-code'
    | '/api/email/verify-code'
    | '/exchange/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BuyRoute: typeof BuyRoute
  BuyCryptoRoute: typeof BuyCryptoRoute
  DashboardRoute: typeof DashboardRoute
  ExchangeRoute: typeof ExchangeRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwapRoute: typeof SwapRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ApiEmailSendCodeRoute: typeof ApiEmailSendCodeRoute
  ApiEmailVerifyCodeRoute: typeof ApiEmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-crypto': {
      id: '/buy-crypto'
      path: '/buy-crypto'
      fullPath: '/buy-crypto'
      preLoaderRoute: typeof BuyCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/': {
      id: '/exchange/'
      path: '/'
      fullPath: '/exchange/'
      preLoaderRoute: typeof ExchangeIndexRouteImport
      parentRoute: typeof ExchangeRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/checkout': {
      id: '/exchange/checkout'
      path: '/checkout'
      fullPath: '/exchange/checkout'
      preLoaderRoute: typeof ExchangeCheckoutRouteImport
      parentRoute: typeof ExchangeRoute
    }
    '/exchange/order/$orderId': {
      id: '/exchange/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/exchange/order/$orderId'
      preLoaderRoute: typeof ExchangeOrderOrderIdRouteImport
      parentRoute: typeof ExchangeRoute
    }
    '/api/email/verify-code': {
      id: '/api/email/verify-code'
      path: '/api/email/verify-code'
      fullPath: '/api/email/verify-code'
      preLoaderRoute: typeof ApiEmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send-code': {
      id: '/api/email/send-code'
      path: '/api/email/send-code'
      fullPath: '/api/email/send-code'
      preLoaderRoute: typeof ApiEmailSendCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExchangeRouteChildren {
  ExchangeCheckoutRoute: typeof ExchangeCheckoutRoute
  ExchangeIndexRoute: typeof ExchangeIndexRoute
  ExchangeOrderOrderIdRoute: typeof ExchangeOrderOrderIdRoute
}

const ExchangeRouteChildren: ExchangeRouteChildren = {
  ExchangeCheckoutRoute: ExchangeCheckoutRoute,
  ExchangeIndexRoute: ExchangeIndexRoute,
  ExchangeOrderOrderIdRoute: ExchangeOrderOrderIdRoute,
}

const ExchangeRouteWithChildren = ExchangeRoute._addFileChildren(
  ExchangeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BuyRoute: BuyRoute,
  BuyCryptoRoute: BuyCryptoRoute,
  DashboardRoute: DashboardRoute,
  ExchangeRoute: ExchangeRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwapRoute: SwapRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ApiEmailSendCodeRoute: ApiEmailSendCodeRoute,
  ApiEmailVerifyCodeRoute: ApiEmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
